name: Bug Report
description: Report a bug or unexpected behavior in shape-http
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: When I parse an HTTP request with chunked encoding, I get an unexpected error...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create an HTTP request with '...'
        2. Parse it using '...'
        3. Observe error '...'
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected the parser to successfully parse the request and return...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, I got an error...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      render: go
      placeholder: |
        package main

        import "github.com/shapestone/shape-http/pkg/http"

        func main() {
            // Your code here
        }

  - type: textarea
    id: input
    attributes:
      label: Input Data
      description: If applicable, provide the HTTP message that causes the issue
      placeholder: |
        GET /path HTTP/1.1
        Host: example.com

  - type: input
    id: version
    attributes:
      label: shape-http Version
      description: What version of shape-http are you using?
      placeholder: v0.1.0
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using?
      placeholder: go1.23.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: macOS 14.0, Ubuntu 22.04, Windows 11
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (logs, screenshots, etc.)
      placeholder: |
        Stack trace:
        ...
